### ISSUE TITLE
Thêm Paging, Searching, Filtering cho các Module quản lý độc giả, sách, thư mục, nhà xuất bản, tác giả

### ISSUE THREAD

**Issue by khanh96le** [khanh96le/QuanLyThuVien#3]
Thêm tương tự như phần Librarian

**Comment by hungMta** [comment]
I am going to help you

**Comment by khanh96le** [comment]
thanks. I'm glad to receive a pull request from you

**Comment by hungMta** [comment]
but you're using a bad template , so we have to do so much things

**Comment by khanh96le** [comment]
Close this isssue
